var Constants = {
  PROFILE_RECEIVED: "PROFILE_RECEIVED",
  USERS_RECEIVED: "USERS_RECEIVED",
  USER_RECEIVED: "USER_RECEIVED",
  USER_UPDATED: "USER_UPDATED",

  GAMES_RECEIVED: "GAMES_RECEIVED",
  GAME_RECEIVED: "GAME_RECEIVED",
  GAME_REMOVED: "GAME_REMOVED",

  SEARCH_PARAMS_RECEIVED: "SEARCH_PARAMS_RECEIVED",
  CURRENT_USER_RECEIVED: "CURRENT_USER_RECEIVED"
}

module.exports = Constants;
